AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation template for Module 1 Setup
Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: LambdaLogsPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
  MyLambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: my-lambda-layer
      Description: My Lambda Layer
      Content:
        S3Bucket: package-lambda-2023
        S3Key: v0.0.1/09135be1c6f282d3acde618962755cff
      CompatibleRuntimes:
      - nodejs18.x
  MyLambdaFn:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: cfn-workshop-node-function
      Description: Node Function to do stuff
      Runtime: nodejs18.x
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Handler: app.lambdaHandler
      Code:
        S3Bucket: package-lambda-2023
        S3Key: v0.0.1/1da5b48861ab26efae436db2345be7c6
      Timeout: 15
      MemorySize: 128
      Layers:
      - Ref: MyLambdaLayer
