AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cloudformation template for Module 1 Setup'

Resources:
  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service: "lambda.amazonaws.com"
          Action:
          - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "LambdaLogsPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: "Allow"
              Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
              Resource: "arn:aws:logs:*:*:*"
  MyLambdaFn:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: cfn-workshop-node-function
      Description: Node Function to do stuff
      Runtime: nodejs18.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Handler: index.CostCalculator
      Code: ./functions # <<< This is a local directory
      Timeout: 15
      MemorySize: 128

